apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smitele-bot.fullname" . }}
  labels:
    {{- include "smitele-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  discordToken: {{ required "credentials.discordToken required in values.local.yaml" .Values.credentials.discordToken | quote }}
  hirezDevId: {{ required "credentials.hirezDevId required in values.local.yaml" .Values.credentials.hirezDevId | quote }}
  hirezAuthKey: {{ required "credentials.hirezAuthKey required in values.local.yaml" .Values.credentials.hirezAuthKey | quote }}
